# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
concurrency:
  group: metrics-${{ github.ref }}
  cancel-in-progress: true
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "metrics 1"
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with: 
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics-1.svg"
          base: header
          config_timezone: Asia/Tokyo
          config_display: large
          config_order: base.header, isocalender
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      - name: "metrics 2"
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics-2.svg"
          base: ""
          config_timezone: Asia/Tokyo
          config_display: large
          config_order: languages, habits,　topics
          #, achivements
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_colors: github
          plugin_languages_limit: 8
          
          #plugin_achievements: yes
          #plugin_achievements_display: detailed
          #plugin_achievements_secrets: yes    
      - name: "collect metrics images"
        run: |
          mkdir tmp
          sudo cp /metrics_renders/metrics-1.svg ./tmp/
          sudo cp /metrics_renders/metrics-2.svg ./tmp/
          sudo chown -R "$USER:$USER" tmp
          sudo chmod 644 tmp/*.svg
          [ ! -d assets ] && mkdir assets
          mv tmp/metrics-1.svg assets/
          mv tmp/metrics-2.svg assets/
      - name: "Check current directory"
        run: |
          pwd
          ls -la
          chmod +x .github/scripts/push-assets.bash
      - name: "commit metrics updates"
        run: bash .github/scripts/push-assets.bash
